// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQnbCIVRmcKgTwztG-dSXYz8Kdm-9xOQk',
    appId: '1:293109699602:web:70adf8e50bcead489634cb',
    messagingSenderId: '293109699602',
    projectId: 'tiktok-clone-elian',
    authDomain: 'tiktok-clone-elian.firebaseapp.com',
    storageBucket: 'tiktok-clone-elian.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4prenPaGYLRTyS561Hk_ETbkGDKzeP9U',
    appId: '1:293109699602:android:c02b834f36ff6e1c9634cb',
    messagingSenderId: '293109699602',
    projectId: 'tiktok-clone-elian',
    storageBucket: 'tiktok-clone-elian.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY2M3a83EU44Wh-f3Dyu1RlNa7QVoz1Bs',
    appId: '1:293109699602:ios:5e2c58a4a8e396b09634cb',
    messagingSenderId: '293109699602',
    projectId: 'tiktok-clone-elian',
    storageBucket: 'tiktok-clone-elian.appspot.com',
    androidClientId: '293109699602-2eqvnp256rektpcs3fnmfh3crfmuagev.apps.googleusercontent.com',
    iosClientId: '293109699602-s0n48j7a03903kejippb20dqe6mgp0u0.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
